"""empty message

Revision ID: 4681bc5711d7
Revises: 39280cb784d1
Create Date: 2025-05-17 18:53:48.039922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4681bc5711d7'
down_revision = '39280cb784d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.DateTime(), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=12288),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_article_edited'), ['edited'], unique=False)

    with op.batch_alter_table('article_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('body', sa.String(length=1024), nullable=False))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_article_comment_created'), ['created'], unique=False)
        batch_op.drop_column('comment_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('phone_number_last_digits',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_number_last_digits',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('article_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_article_comment_created'))
        batch_op.drop_column('created')
        batch_op.drop_column('body')
        batch_op.drop_column('id')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_edited'))
        batch_op.alter_column('body',
               existing_type=sa.String(length=12288),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
