"""empty message

Revision ID: 6002f82c8138
Revises: 8dc7ca1b1add
Create Date: 2025-05-30 23:50:50.371720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6002f82c8138'
down_revision = '8dc7ca1b1add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_comment_edited'), ['edited'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_edited'))
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
