"""empty message

Revision ID: 7a9258d150b1
Revises: 6002f82c8138
Create Date: 2025-05-30 23:53:01.988039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9258d150b1'
down_revision = '6002f82c8138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('edited',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('edited',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
